### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [15]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[53, 74, 35, 16],
       [48, 50, 79, 47],
       [22, 53, 30,  8],
       [79, 20,  6, 44],
       [26, 50, 63, 94],
       [ 6, 23, 83,  4]])

In [16]:
np.sort(a)[::-1]

array([94, 92, 67, 60, 57, 49, 48, 46, 43, 31, 28, 27, 23, 15,  9])

In [18]:
np.sort(b,axis=0) #rowise

array([[ 6, 20,  6,  4],
       [22, 23, 30,  8],
       [26, 50, 35, 16],
       [48, 50, 63, 44],
       [53, 53, 79, 47],
       [79, 74, 83, 94]])

In [20]:
np.sort(b,axis=1) #columnwise

array([[16, 35, 53, 74],
       [47, 48, 50, 79],
       [ 8, 22, 30, 53],
       [ 6, 20, 44, 79],
       [26, 50, 63, 94],
       [ 4,  6, 23, 83]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [21]:
# code
np.append(a,200)

array([ 15,  60,  28,  48,  46,  67,  31,  57,  92,  49,   9,  23,  43,
        94,  27, 200])

In [22]:
b

array([[53, 74, 35, 16],
       [48, 50, 79, 47],
       [22, 53, 30,  8],
       [79, 20,  6, 44],
       [26, 50, 63, 94],
       [ 6, 23, 83,  4]])

In [23]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[5.30000000e+01, 7.40000000e+01, 3.50000000e+01, 1.60000000e+01,
        7.58526744e-01],
       [4.80000000e+01, 5.00000000e+01, 7.90000000e+01, 4.70000000e+01,
        6.78293343e-02],
       [2.20000000e+01, 5.30000000e+01, 3.00000000e+01, 8.00000000e+00,
        7.90106223e-01],
       [7.90000000e+01, 2.00000000e+01, 6.00000000e+00, 4.40000000e+01,
        1.72590300e-01],
       [2.60000000e+01, 5.00000000e+01, 6.30000000e+01, 9.40000000e+01,
        6.40327052e-01],
       [6.00000000e+00, 2.30000000e+01, 8.30000000e+01, 4.00000000e+00,
        7.47401404e-02]])

In [24]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[53., 74., 35., 16.,  1.],
       [48., 50., 79., 47.,  1.],
       [22., 53., 30.,  8.,  1.],
       [79., 20.,  6., 44.,  1.],
       [26., 50., 63., 94.,  1.],
       [ 6., 23., 83.,  4.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [25]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [26]:
# rowise concatenation
# concatenation similar to hstacking
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
# colswise concatenation
# concatenation similar to vstacking
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [28]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [31]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [32]:
# code
a.shape

(15,)

In [33]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [35]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [37]:
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [38]:
# find all indices with value greater than 50
# return index position where
# it's greater than 50
np.where(a>50)

(array([ 1,  5,  7,  8, 13], dtype=int64),)

In [39]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([15,  0, 28, 48, 46,  0, 31,  0,  0, 49,  9, 23, 43,  0, 27])

In [40]:
np.where(a%2 == 0,0,a)

array([15,  0,  0,  0,  0, 67, 31, 57,  0, 49,  9, 23, 43,  0, 27])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [42]:
# return index position  of 
# element which is maximum
np.argmax(a)

13

In [43]:
b

array([[53, 74, 35, 16],
       [48, 50, 79, 47],
       [22, 53, 30,  8],
       [79, 20,  6, 44],
       [26, 50, 63, 94],
       [ 6, 23, 83,  4]])

In [45]:
# column wise
np.argmax(b,axis=0)

array([3, 0, 5, 4], dtype=int64)

In [46]:
# row wise
np.argmax(b,axis=1)

array([1, 2, 1, 0, 3, 2], dtype=int64)

In [47]:
# np.argmin
np.argmin(a)

10

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [48]:
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [49]:
np.cumsum(a)

array([ 15,  75, 103, 151, 197, 264, 295, 352, 444, 493, 502, 525, 568,
       662, 689])

In [50]:
b

array([[53, 74, 35, 16],
       [48, 50, 79, 47],
       [22, 53, 30,  8],
       [79, 20,  6, 44],
       [26, 50, 63, 94],
       [ 6, 23, 83,  4]])

In [52]:
np.cumsum(b,axis=0) #cols. wise

array([[ 53,  74,  35,  16],
       [101, 124, 114,  63],
       [123, 177, 144,  71],
       [202, 197, 150, 115],
       [228, 247, 213, 209],
       [234, 270, 296, 213]])

In [53]:
np.cumsum(b,axis=1)

array([[ 53, 127, 162, 178],
       [ 48,  98, 177, 224],
       [ 22,  75, 105, 113],
       [ 79,  99, 105, 149],
       [ 26,  76, 139, 233],
       [  6,  29, 112, 116]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [56]:
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [57]:
np.percentile(a,50)

46.0

In [58]:
np.median(a)

46.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [67]:
np.histogram(a,bins=[0,10,20,30])

(array([1, 1, 3], dtype=int64), array([ 0, 10, 20, 30]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html


![Alt text](np.coref.png)

In [68]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [69]:
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [72]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [73]:
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [74]:
np.flip(a)

array([27, 94, 43, 23,  9, 49, 92, 57, 31, 67, 46, 48, 28, 60, 15])

In [75]:
b

array([[53, 74, 35, 16],
       [48, 50, 79, 47],
       [22, 53, 30,  8],
       [79, 20,  6, 44],
       [26, 50, 63, 94],
       [ 6, 23, 83,  4]])

In [76]:
np.flip(b,axis=1)

array([[16, 35, 74, 53],
       [47, 79, 50, 48],
       [ 8, 30, 53, 22],
       [44,  6, 20, 79],
       [94, 63, 50, 26],
       [ 4, 83, 23,  6]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [77]:
a

array([15, 60, 28, 48, 46, 67, 31, 57, 92, 49,  9, 23, 43, 94, 27])

In [80]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  28,  48,  46,  67,  31,  57,  92,  49,   9,  23,  43,
        94,  27])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [79]:
a

array([110, 530,  28,  48,  46,  67,  31,  57,  92,  49,   9,  23,  43,
        94,  27])

In [82]:
np.delete(a,[0,2,4])

array([530,  48,  67,  31,  57,  92,  49,   9,  23,  43,  94,  27])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [83]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [84]:
np.intersect1d(m,n)

array([3, 4, 5])

In [85]:
# (m) mein hai par not in (n)
np.setdiff1d(n,m)

array([6, 7])

In [86]:
# common wale ko hatake baaki
# rakh lega
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [87]:
# 1 hai (m) mein
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [88]:
a

array([110, 530,  28,  48,  46,  67,  31,  57,  92,  49,   9,  23,  43,
        94,  27])

In [89]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 48, 46, 67, 31, 57, 75, 49, 25, 25, 43, 75, 27])

In [90]:
# 17. np.swapaxes

In [91]:
# 18. np.uniform

In [92]:
# 19. np.count_nonzero

In [93]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [94]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [95]:

# 25. np.allclose and equals