# Numpy - 1

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
import numpy as np

In [4]:
a = np.array([1,2])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
c = np.array([[[1,2,3],[2,2,2]],[[2,33,3],[4,5,6]]])
print(c)

[[[ 1  2  3]
  [ 2  2  2]]

 [[ 2 33  3]
  [ 4  5  6]]]


In [12]:
# np.arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [25]:
# with reshape
np.arange(1,11).reshape(5,2) # (rows,cols)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
# np.ones and np.zeros
print(np.ones((3,2)))

print(np.zeros((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
np.random.random((3,4))

array([[0.39931867, 0.3052888 , 0.92618085, 0.71395074],
       [0.08816129, 0.36286583, 0.48963769, 0.24762972],
       [0.6899797 , 0.00469268, 0.45425182, 0.30297673]])

In [34]:
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [42]:
# np.identity
# 1 in diagnol elements
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [2]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
# ndim
a3.ndim

3

In [4]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
# size
a3.size


8

In [7]:
# itemsize in bytes
a3.itemsize

4

In [8]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [57]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations

In [58]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [60]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [61]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

### Array Functions

In [9]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[11., 50., 33.],
       [10., 48., 43.],
       [ 3., 82., 72.]])

In [10]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([   330., 196800., 102168.])

In [64]:
# mean/median/std/var
np.var(a1,axis=1)

array([ 76.22222222, 280.66666667, 780.22222222])

In [12]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [13]:
# log and exponents
np.exp(a1)

array([[5.98741417e+04, 5.18470553e+21, 2.14643580e+14],
       [2.20264658e+04, 7.01673591e+20, 4.72783947e+18],
       [2.00855369e+01, 4.09399696e+35, 1.85867175e+31]])

In [14]:
#round/floor/cell
np.round(np.random.random((2,3))*100)

array([[  3.,  94.,  51.],
       [ 34.,  48., 100.]])

### Indexing and Slicing

In [17]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a2[2,1]

9

In [20]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
a3[1,0,1]

5

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a = a2[0:2,:3]
a[1,2]

6

### Iterating

In [33]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [37]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [39]:
# reshape
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
# Transpose
np.transpose(a2)


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [42]:
# or
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking


In [47]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [48]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [49]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [55]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]